### ISSUE TITLE
Scrum Update May 29

### ISSUE THREAD

**Issue by nikkimoteva** [nikkimoteva/unDecided#1]
Scrum Update Number 1

Team Name: unDecided (previously TBD)
Nikki Moteva q7s1b
Robert Mo w9d1b
Kian Shahangyan l1a1b
Harry Xv g3z0b

**Comment by KianShah** [comment]
l1a1b
What did you work on this past iteration (2 weeks)?
**I worked with my group on establishing requirements for the AutoML project. We had very little to go off of, so we came up with our ideas for what we should include**
What were any major issues/challenges you ran into?
**We did not run into any issues; mostly we were just brainstorming ideas**
What do you plan to work on for this coming iteration (2 weeks)?
**Building some basic components for the base of the website. Adding a home page, about page, etc, and learning how to upload csv data**

**Comment by nikkimoteva** [comment]
**1. What did you work on this past iteration (2 weeks)?**
     Worked on writing up the requirements and brainstormed some ideas on different task each person has to do.
**2. What were any major issues/challenges you ran into?**
     Thinking about different scenarios regarding the usage of the backend.
**3. What do you plan to work on for this coming iteration (2 weeks)?**
     Will start the project boilerplate and work on the about page and the start page with my other teammates.

**Comment by aestrr** [comment]
**What did you work on this past iteration (2 weeks)?**
brainstorming issues
**What were any major issues/challenges you ran into?**
there were no major issues
**What do you plan to work on for this coming iteration (2 weeks)?**
working on the minimal UI requirement for the website

**Comment by robertmzm** [comment]
1. What did you work on this past iteration (2 weeks)?
Brainstormed project idea and requirement
2. What were any major issues/challenges you ran into?
I did not run into any major issues.
3. What do you plan to work on for this coming iteration (2 weeks)?
I will get the basic styling setup and look into the user scenario
W9D1B
