### ISSUE TITLE
Scrum Update June 12

### ISSUE THREAD

**Issue by nikkimoteva** [nikkimoteva/unDecided#11]
Scrum Update Number 2

Team Name: unDecided
Nikki Moteva q7s1b
Robert Mo w9d1b
Kian Shahangyan l1a1b
Harry Xv g3z0b

**Comment by nikkimoteva** [comment]
1. What did you work on this past iteration (2 weeks)?
Set up the frontend, and worked on the different components of our website. I worked on the front page component, and re-routing the main page to some of the other pages. I also added some designs to the components.
2. What were any major issues/challenges you ran into?
Learning about material-ui and incorporating it into the code.
3. What do you plan to work on for this coming iteration (2 weeks)?
Will finish up the main page, and start working on the backend of the website. Will also play around with the autoML API (if provided before the deadline) to check for any backend innovations we could work on.

**Comment by KianShah** [comment]
1. **What did you work on this past iteration (2 weeks)?**
- Developed the Header and Login pages using React components. Also I resolved merge conflicts and delivered the final product to the `project_2` branch
2. **What were any major issues/challenges you ran into?**
- Had lots of merge conflicts, and we ran into an issue with using both npm and yarn at the same time. We decided to migrate to using yarn as it seems like a better alternative and switching to it required minimal changes.
3. **What do you plan to work on for this coming iteration (2 weeks)?**
- FIxing up the header and login pages, and overall finalizing the design for the website. Will also look into building the views/pages for when a user logs into our site

**Comment by robertmzm** [comment]
What did you work on this past iteration (2 weeks)?

Developed the signup page using React components.

What were any major issues/challenges you ran into?
Trying out different styling options for materialUI is tricky and it took me a long time to create styling for multiply CSS class within a component

What do you plan to work on for this coming iteration (2 weeks)?
Make proper styling for the signup page and link the correspond page after a signup form is submitted.

**Comment by aestrr** [comment]
1. What did you work on this past iteration (2 weeks)?
developed the demo page of our webapp using material ui and react

2. What were any major issues/challenges you ran into?
styling the page to be presentable for the demo

3. What do you plan to work on for this coming iteration (2 weeks)?
starting working on the server side of the project
