### ISSUE TITLE
ESLINT Cleanup

### ISSUE THREAD

**Issue by nikkimoteva** [nikkimoteva/unDecided#28]
Cleanup for esLint. Please clean up the warnings from the files that you worked on.

**Comment by nikkimoteva** [comment]
c0d5b1f4ec67032448dc659aee47932c6e2f19f5

**Comment by KianShah** [comment]
Closing this cause most major fixes have already been made, aside from some unused vars warnings. We should aim to keep the project free of linting issues as much as possible
