### ISSUE TITLE
Scrum Update July 18th

### ISSUE THREAD

**Issue by aestrr** [nikkimoteva/unDecided#51]
CS ID: g3z0b

1. What did you work on this past iteration (2 weeks)?
Rewrote blackboxml endpoints for submitting training and prediction commands to ensemble^2

2. What were any major issues/challenges you ran into?
Learning python and research/test out js modules that help with my tasks, ssh connection

3. What do you plan to work on for this coming iteration (2 weeks)?
Connecting with ensemble^2 that is being hosted, combine endpoints and any additional backend/frontend work

**Comment by nikkimoteva** [comment]
CSID: q7s1b

What did you work on this past iteration (3 weeks)?
Landing page, contact us page, logo with Robert, database with Kian, jobs page design with Robert.

What were any major issues/challenges you ran into?
Breaking tasks down into smaller tasks, not working closer with Kian on the DB due to conflicting schedules.

What do you plan to work on for this coming iteration (2 weeks)?
Implement user login, deploy our code to Heroku.

**Comment by KianShah** [comment]
CS id: l1a1b

**What did you work on this past iteration (3 weeks)?**
Implemented AWS import functionality, added database functionality, added sample job and user data, implemented temporary fix for the user id token issue (made user email the _id of each user), coordinated with all team members to help them accomplish their tasks

**What were any major issues/challenges you ran into?**
Lots of functionality conflicts that caused breakage in the dev branch

**What do you plan to work on for this coming iteration (2 weeks)?**
Fix the job form, fix bugs, and fix the AWS import data form. Also, will probably help Robert with the Jobs page

**Comment by robertmzm** [comment]
CS ID: w9d1b
What did you work on this past iteration (3 weeks)?
Implemented Job page table. Worked on styling on jobs form. Debug and fixed some of the endpoints relating to jobs. Made minor adjustment on the logo.

What were any major issues/challenges you ran into?
Workload estimation, merge conflict and communication. 

What do you plan to work on for this coming iteration (2 weeks)?
styling on jobs table, research on XGrid and job prediction implementation
