### ISSUE TITLE
Scrum Update July 31

### ISSUE THREAD

**Issue by nikkimoteva** [nikkimoteva/unDecided#99]
Team Name: unDecided
Nikki Moteva q7s1b
Robert Mo w9d1b
Kian Shahangyan l1a1b
Harry Xv g3z0b

**Comment by nikkimoteva** [comment]
Nikki Moteva q7s1b

1. What did you work on this past iteration (2 weeks)?
Users' database, email sign up and sign in, email and password security, storing data on local machine, bug fixes in different parts of the code.
2. What were any major issues/challenges you ran into?
Learning about user securities, merge conflicts.
3. What do you plan to work on for this coming iteration (2 weeks)?
I will work on storing AWS credentials in the database, code cleanup, bug fixes, sending results email, also maybe profile page, documentations, and demo if my other teammates need extra help.

**Comment by KianShah** [comment]
Kian Shahangyan l1a1b

**What did you work on this past iteration (2 weeks)?**

Fixed the job form, made the prediction job form, fixed the AWS import data form, helped Harry with connecting to ensemble-squared. Also did the integrating the ensemble-squared backend with our backend.

**What were any major issues/challenges you ran into?**

Lots of merge/functionality conflicts. Lots of stuff randomly breaking.

**What do you plan to work on for this coming iteration (2 weeks)?**

Cleaning up my code. Finish implementing download prediction files. Work with Nikki on implementing a way for users to save their AWS credentials. Display CSV when user submits it. Help with documentation if needed

**Comment by aestrr** [comment]
Harry Xu g3z0b 

What did you work on this past iteration (2 weeks)?
ssh into ensemble squared, running job submissions to ensemble squared

What were any major issues/challenges you ran into?
understanding ensemble squared python code and postman api testing

What do you plan to work on for this coming iteration (2 weeks)?
getting job queue data and parsing them for front end to use as endpoints

**Comment by robertmzm** [comment]
Robert Mo W9D1B

What did you work on this past iteration (2 weeks)?

prediction page, prediction submission, job status update, job deletion

What were any major issues/challenges you ran into?

Merge conflicts and build issue.


What do you plan to work on for this coming iteration (2 weeks)?

Cleanup Code, Progress bar, documentation and styling
